logging:
  level: INFO

paths:
  raw_crypto: data/raw_crypto/       # whatever you like

data:
  crypto_api: https://api.binance.com/api/v3/klines
  interval: 1h
  limit: 500

symbols:
  crypto: [BTCUSDT, ETHUSDT]
